version: 2.1
jobs:
  build:
    docker:
      - image: node:12-stretch
    parallelism: 2
    environment:
      BLENDER_MAJOR: 2
      BLENDER_MINOR: 83
      TEST_FILTERS: >-
        blender_export
        blender_roundtrip
    steps:
      - checkout
      - run:
          name: Install Blender
          no_output_timeout: 20m
          command: |
            FILTERS=($TEST_FILTERS)
            FILTER=${FILTERS[$CIRCLE_NODE_INDEX]}
            echo "FILTER: '$FILTER'"
            export DEBIAN_FRONTEND=noninteractive
            apt -q update && apt install --no-install-recommends -y -q \
              libglu1-mesa \
              libxi6
            echo "Looking for: Blender $BLENDER_MAJOR.$BLENDER_MINOR"
            BLENDER_URL="https://builder.blender.org$(curl -s https://builder.blender.org/download/ | \
              grep -oe '[^\"]*blender-'$BLENDER_MAJOR'\.'$BLENDER_MINOR'[^\"]*linux64[^\"]*' | \
              tail -n1)"
            mkdir /opt/blender
            echo "Downloading from: $BLENDER_URL"
            curl -SL "$BLENDER_URL" | \
              tar -Jx -C /opt/blender --strip-components=1
            ln -s /opt/blender/blender /usr/local/bin/blender
            blender --version
      - run:
          name: Setup Tests
          command: |
            ADDON_DIR=/opt/blender/$BLENDER_MAJOR.$BLENDER_MINOR/scripts/addons
            rm -rf $ADDON_DIR/io_scene_gltf2
            cp -r addons/io_scene_gltf2 $ADDON_DIR
            cd tests
            yarn install
            mkdir -p /out
      - run:
          name: Run Tests
          command: |
            FILTERS=($TEST_FILTERS)
            FILTER=${FILTERS[$CIRCLE_NODE_INDEX]}
            cd tests
            OUT_PREFIX=/out yarn test-bail --reporter-options reportDir=/out/mochawesome -g $FILTER
      - store_artifacts:
          path: /out
